version: "3.9"
services:
  mkdocs:
    #image: fyliu/local-mkdocs:testing
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs
    command: mkdocs serve -a "0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
